# Generated by Django 3.2.18 on 2023-05-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.TextField(unique=True)),
                ('cur_nm', models.TextField()),
                ('deal_bas_r', models.TextField()),
            ],
        ),
    ]
