# Generated by Django 3.2.18 on 2023-05-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_id_user_realname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_proudct',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
